### PR TITLE
Update README.md - minor typo and one suggested addition

### PR DESCRIPTION
**Pull request by jbuberel**
Fixed the 'arguably' (was arguable), and added a note that Google Cloud also offers Redis as a service.

### CODE REVIEW

**Comment by albrow** [comment]
@jbuberel, thank you for this fix. I know it's small but every bit helps :)

As described in the [contributing](https://github.com/albrow/zoom#contributing) section of the README, pull requests should request to be merged into develop, not master. This helps me to manage the branching model and version numbers in a sane way. Would you mind changing the base branch (where you intend the PR to be merged into) to albrow:develop? You may need to close this PR and create a new one.

**Comment by albrow** [comment]
@jbuberel, it's been 3 days since you first opened this PR. I would like to be able to give you credit for this small fix. If you can close this and submit a new PR to be merged into the develop branch, I'll merge it and include it in the next release. Otherwise, I'm going to just make the fix myself this weekend.

I'm also going to copy the contributing section to a CONTRIBUTING.md file to make sure more people can find it. Hope to hear from you again soon!

**Comment by albrow** [comment]
Since I haven't heard back from you, I made the fix myself at https://github.com/albrow/zoom/commit/75285bbbe3cfca332016feb7d3bab7f30f555262. Thank you for pointing out the typo! Please don't hesitate to open more issues or PRs in the future :)

**Comment by jbuberel** [comment]
And apologies for my not either (a) responding more quickly or (b) reading your contribution docs first!

**Pull request closed without merging**
